CHUNK_SIZE = 16
CHUNK_CHANGED_EVENT_NAME = 'chunk_changed'
CHUNK_CREATED_EVENT_NAME = 'chunk_loaded'
CHUNK_DESTROYED_EVENT_NAME = 'chunk_destroyed'
DEBUG_WORLD_GEN_TILE_TYPE = 'stone'
DEBUG_SHOW_CHUNK_BORDERS = False
CHUNK_BORDER_COLOR = (100,100,100)

zone_dict = {}